name: Build and Test

on:
  workflow_call:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    strategy:
      matrix:
        elixir: ["1.11.4", "1.12.3", "1.13.4"]
        otp: ["22.3", "23.3", "24.3"]
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ex_audit_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Elixir Project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
          build-flags: --all-warnings --warnings-as-errors

      - name: Run Migrations
        run: mix ecto.migrate
        if: always()

      - name: Run Tests
        run: mix coveralls.json
        if: always()

      # Optional, but Codecov has a bot that will comment on your PR with per-file
      # coverage deltas.
      - name: Upload to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./cover/excoveralls.json

